### ISSUE TITLE
[Report] Quality of suggestions

### ISSUE THREAD

**Issue by jijiangli-swu-worker** [yoterel/nepmap#5]
Hi,
Thank you for sharing your implementation, especially the Blender script! I found it relatively straightforward to reproduce the results from your paper. However, I did encounter a few minor bugs when testing with custom datasets that you might want to address.
1. **Mismatch with function return** [here](https://github.com/yoterel/nepmap/blob/1c8557add2140275a3de8cbaa3d0c06040e7fdef/data/data_loader.py#L18C3-L18C25) return as one value `texture ids`, when call this func in [here](https://github.com/yoterel/nepmap/blob/1c8557add2140275a3de8cbaa3d0c06040e7fdef/data/data_loader.py#L69C9-L70C72) it recieves two values `texture_ids` and `texture_names`, just remove the texture_ids could fix this.
2. I test in Windows [this function called](https://github.com/yoterel/nepmap/blob/1c8557add2140275a3de8cbaa3d0c06040e7fdef/data/data_loader.py#L87) x, y may due to the system difference, they are not match in order to generate right img2tex.json with correct mathing names and ids.
``` python
file_names.sort(key=lambda name: int(re.findall(r'\d+', name)[0]))
```
this line can guarantee the correct order to such json file in my systems

Overall, everything else went smoothly, and I was able to easily reproduce some of the results.
Best.

**Comment by yoterel** [comment]
Thanks !

Unfortunately I have no way to test the changes as I don't use windows (and I don't intend to create a github workflow), is there any chance I can ask you to submit a pull request that exactly solves the issues you mentioned?

It has been a while since I reviewed this code, but for issue (1) you mentioned, the calling function that uses "get_pattern_names" looks like it computes something from texture_ids, so removing it shouldn't work. How did you get around this?

Appreciate your comment.

**Comment by jijiangli-swu-worker** [comment]
Hi, 
1. Thank you for your prompt response and kind help. Regarding the mismatch in the function call, I made the following changes to ensure the function is called correctly. As you mentioned, both textures_ids and textures_names will be used later.

``` python
"""
        This is processing the patteren
        @function get_pattern_names:
            return all projector pattern with id and names in texture_ids, texture_names
"""
def get_pattern_names(amount, length, voronoi_amount=3):
    pattern_amount = amount
    pattern_length = length
    sync_time = length
    x = np.arange(0, pattern_amount).repeat(pattern_length)
    indices = np.where(np.ediff1d(x, to_begin=1, to_end=1))[0]
    x = np.insert(x, np.repeat(indices, pattern_length), -1)
    indices = np.where(np.ediff1d(x) > 0)[0] + 1
    x = np.insert(x, np.repeat(indices, sync_time), -2)
    x = np.concatenate((x, np.repeat(-2, sync_time)))
    y = np.empty(len(x), dtype='<U16')
    y[x==-2] = "all_black"
    y[x==-1] = "all_white"
    #lollipop
    for i in range(pattern_amount):
        y[x==i] = "lollipop_{}".format(i)
    # for i in range(voronoi_amount):
    #     y[x==i] = "voronoi_{}".format(i)
    # for i in range(voronoi_amount, pattern_amount):
    #     y[x==i] = "gray_{}".format(i)
    selected_textures = y
    # if len(selected_textures) < N_VIEWS:
    #     selected_textures = np.concatenate((selected_textures, np.full(N_VIEWS - len(selected_textures), "all_black")))
    return x,selected_textures
```
2. I apologize for not being able to test the logic at the moment. However, I will do so later when working with a custom datasets, and I would be more than happy to submit a request then if it's truly necessary. 

3. By the way, it would be helpful to specify the dataset logic in the README, as I encountered the same question mentioned in [this link ](https://github.com/yoterel/nepmap/issues/4)during my testing. For example, if I understand correctly, the logic could be as follows:
      xxx_random: test dataset
      xxx: train with the second and third stage
      xxx_coloc: train with Voronoi Nerf
      Providing this clarification could be beneficial for users.

Anyway, thank you for your excellent work—it's truly beneficial for multi-view PM modeling.
